### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by tenorz007** [mojoblanco/NUBAN#7]
I think there should be CI that checks if the implementations are valid as a build step.

**Comment by mojoblanco** [comment]
That is a nice idea but since this is not like an application and people are allowed to submit different implementations per programming language, it would be cumbersome to create tests for each implementations (not unless each contributor attaches his/her own tests). I try to test for the implementations I can and they have been working so far.
If there is a better way to go about it, I'm open to suggestions.
Thanks 👍

**Comment by tenorz007** [comment]
So my reasoning is this; the code is meant to the same thing, just across different languages. The language implementation would still remain a black box but the input and output should be supplied and expected in a uniform way. For instance; the input could be supplied as standard input of two lines where the first is the bank code, and the second is the account. When either of those are wrong or supplied incorrectly, what then is the expected behavior? I was just feeling that it would be nice if they are behave identically irrespective of ports.

**Comment by mojoblanco** [comment]
That is actually a good suggestion. Those that made it that way made it easier for me to test (even though I have no idea about the language) as long as I run them. 
I would try to inform those that did otherwise to try and update their codes.
Thanks.

**Comment by tenorz007** [comment]
Perhaps you can even create a test suite that people should run it against if you don't feel like going the complicated route.
